import pandas as pd

from app.services.csv_service import build_business_summary

DEMO_ROWS = [
    {
        "date": "2026-01-05",
        "product_name": "Pamuk Oversize T-Shirt",
        "category": "Giyim",
        "supplier": "ModaTedarik",
        "sales_quantity": 42,
        "revenue": 18900,
        "cost": 11340,
        "return_quantity": 4,
        "return_reason": "Beden uyumsuz",
    },
    {
        "date": "2026-01-08",
        "product_name": "Keten Yazlik Elbise",
        "category": "Giyim",
        "supplier": "ModaTedarik",
        "sales_quantity": 28,
        "revenue": 22400,
        "cost": 14560,
        "return_quantity": 6,
        "return_reason": "Renk farki",
    },
    {
        "date": "2026-01-12",
        "product_name": "Deri Capraz Canta",
        "category": "Aksesuar",
        "supplier": "AksesuarPlus",
        "sales_quantity": 19,
        "revenue": 28500,
        "cost": 17100,
        "return_quantity": 2,
        "return_reason": "Hasarli urun",
    },
    {
        "date": "2026-01-15",
        "product_name": "Seramik Kahve Kupasi Seti",
        "category": "Ev Yasam",
        "supplier": "EvKonfor",
        "sales_quantity": 35,
        "revenue": 12250,
        "cost": 7350,
        "return_quantity": 3,
        "return_reason": "Kirik parca",
    },
    {
        "date": "2026-01-18",
        "product_name": "Aromaterapi Mum Seti",
        "category": "Ev Yasam",
        "supplier": "EvKonfor",
        "sales_quantity": 48,
        "revenue": 14400,
        "cost": 7920,
        "return_quantity": 5,
        "return_reason": "Koku beklentisi",
    },
    {
        "date": "2026-01-22",
        "product_name": "Bluetooth Kulaklik",
        "category": "Elektronik",
        "supplier": "TeknoKaynak",
        "sales_quantity": 31,
        "revenue": 27900,
        "cost": 19530,
        "return_quantity": 7,
        "return_reason": "Baglanti sorunu",
    },
    {
        "date": "2026-01-25",
        "product_name": "Akıllı Saat Kordonu",
        "category": "Elektronik",
        "supplier": "TeknoKaynak",
        "sales_quantity": 26,
        "revenue": 7800,
        "cost": 3900,
        "return_quantity": 1,
        "return_reason": "Yanlis model",
    },
    {
        "date": "2026-02-02",
        "product_name": "Organik Bebek Body",
        "category": "Bebek",
        "supplier": "MiniDunya",
        "sales_quantity": 37,
        "revenue": 11100,
        "cost": 6660,
        "return_quantity": 2,
        "return_reason": "Beden uyumsuz",
    },
    {
        "date": "2026-02-06",
        "product_name": "Yün Triko Kazak",
        "category": "Giyim",
        "supplier": "ModaTedarik",
        "sales_quantity": 24,
        "revenue": 19200,
        "cost": 12480,
        "return_quantity": 5,
        "return_reason": "Tiftiklenme",
    },
    {
        "date": "2026-02-10",
        "product_name": "Paslanmaz Termos",
        "category": "Ev Yasam",
        "supplier": "EvKonfor",
        "sales_quantity": 29,
        "revenue": 14500,
        "cost": 8700,
        "return_quantity": 2,
        "return_reason": "Sizinti",
    },
    {
        "date": "2026-02-14",
        "product_name": "Spor Tayt",
        "category": "Giyim",
        "supplier": "AktifLine",
        "sales_quantity": 33,
        "revenue": 16500,
        "cost": 9900,
        "return_quantity": 4,
        "return_reason": "Kalite beklentisi",
    },
    {
        "date": "2026-02-18",
        "product_name": "Çocuk Oyuncak Seti",
        "category": "Bebek",
        "supplier": "MiniDunya",
        "sales_quantity": 22,
        "revenue": 8800,
        "cost": 5280,
        "return_quantity": 3,
        "return_reason": "Eksik parca",
    },
]


def get_demo_business_summary() -> dict:
    df = pd.DataFrame(DEMO_ROWS)
    return build_business_summary(df)
